version: '3.9'


networks:
  br-network:
    name: br-network
    driver: bridge

services:
  app: &app
    build:
      context: .
      dockerfile: compose/local.Dockerfile
    container_name: br_app_local
    command: /start
    restart: always
    env_file:
      - local.env
    volumes:
      - ./app:/opt/br/
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    networks:
      - br-network

  postgres:
    image: postgres:13-alpine
    container_name: br_postgres_local
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - local.env
    environment:
      - TZ=Europe/Moscow
    ports:
      - "5432:5432"
    networks:
      - br-network


  redis:
    image: valkey/valkey:7.2.5-alpine3.19
    container_name: br_redis_local
    restart: always
    ports:
      - "6379:6379"
    networks:
      - br-network
    volumes:
      - redis_data:/data


  celery_worker:
    <<: *app
    container_name: br_celery_worker_local
    restart: always
    env_file:
      - local.env
    volumes:
      - ./app:/opt/br/
    ports: [ ]
    command: /start-celeryworker
    networks:
      - br-network
    depends_on:
      - redis
      - postgres

  celery_beat:
    <<: *app
    container_name: br_celery_beat_local
    restart: always
    env_file:
      - local.env
    volumes:
      - ./app:/opt/br/
    ports: [ ]
    command: /start-celerybeat
    networks:
      - br-network
    depends_on:
      - redis
      - postgres

  flower:
    <<: *app
    container_name: br_flower_local
    command: /start-flower
    restart: always
    env_file:
      - local.env
    ports:
      - "5555:5555"
    networks:
      - br-network
    depends_on:
      - celery_worker
      - celery_beat
      - redis

#  nginx_exporter:
#    image: nginx/nginx-prometheus-exporter:0.10.0
#    container_name: br_nginx_exporter
#    ports:
#      - "9113:9113"
#    environment:
#      - NGINX_STATUS_URL=http://br_nginx/nginx_status
#    networks:
#      - br-network
#    depends_on:
#      - nginx
#
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: br_prometheus
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
#    ports:
#      - "9090:9090"
#    networks:
#      - br-network
#    depends_on:
#      - nginx_exporter
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: br_grafana
#    ports:
#      - "3000:3000"
#    networks:
#      - br-network
#    depends_on:
#      - prometheus


volumes:
  postgres_data: {}
  redis_data: {}
