# Generated by Django 5.0.7 on 2024-07-13 23:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bicycles', '0002_alter_bicycle_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'start_time',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                (
                    'total_cost',
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                (
                    'bicycle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rentals',
                        to='bicycles.bicycle',
                    ),
                ),
                (
                    'renter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rentals',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
