# Generated by Django 5.0.7 on 2024-07-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
