global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['br_node_exporter:9100']
  - job_name: 'nginx'
    static_configs:
      - targets: ['br_nginx_exporter:9113']