name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  code_quality:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Check code style (flake8)
        run: |
          flake8 --config app/setup.cfg app

      - name: Check code formatting (black)
        run: |
          black --check --config app/pyproject.toml app

  test_and_coverage:
    runs-on: ubuntu-latest
    needs: code_quality
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker-compose -f local.docker-compose.yml build

      - name: Run tests and upload coverage to Codecov
        run: |
          docker-compose -f local.docker-compose.yml run --rm app sh -c "coverage run --source='.' manage.py test && coverage xml -o /opt/br/coverage.xml"

      - name: Upload coverage to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -f app/coverage.xml


  deploy:
    runs-on: ubuntu-latest
    needs: test_and_coverage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deployment
        env:
          SSH_SERVER: ${{ secrets.SERVER_IP }}
          SSH_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "${SSH_PASSWORD}" \
          ssh -o StrictHostKeyChecking=no "${SSH_USERNAME}"@"${SSH_SERVER}" \
            'cd /opt/deploy/bicycle-rental && \
            docker compose down || true && \
            cd .. && \
            rm -rf bicycle-rental && \
            git clone git@github.com:kolaxy/bicycle-rental.git && \
            cp env bicycle-rental && \
            cd bicycle-rental && \
            docker compose up -d'
