name: Test, Coverage, and Style Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker-compose -f local.docker-compose.yml build

    - name: Run tests and coverage
      run: |
        docker-compose -f local.docker-compose.yml run --rm app sh -c "coverage run --source='.' manage.py test && coverage xml"

    - name: Save coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml

    - name: Generate coverage badge
      run: |
        pip install coverage-badge
        coverage-badge -i -f -o coverage.svg

    - name: Check code style (flake8)
      run: |
        docker-compose -f local.docker-compose.yml run --rm app flake8 .

    - name: Check code formatting (black check)
      run: |
        docker-compose -f local.docker-compose.yml run --rm app black --check .

    - name: Update coverage badge in README
      run: |
        COVERAGE_PERCENTAGE=$(grep "TOTAL" coverage.xml | awk '{print $4}' | tr -d '%')
        sed -i "s|https://img.shields.io/badge/coverage-[0-9]*%25-brightgreen|https://img.shields.io/badge/coverage-${COVERAGE_PERCENTAGE}%25-brightgreen|" README.md

    - name: Push changes to GitHub
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update coverage badge
        branch: main
        commit_options: '--no-verify'
